rollout rapidConformSettings "rapidConformSettings" width:224 height:176
(
	groupBox doubleSidedGrp "DoubleSided" pos:[8,80] width:208 height:88
	checkbox targetFlag "Target" pos:[24,104] width:176 height:16
	checkbox objectFlag "Object" pos:[24,136] width:176 height:16
	bitmap theHeader "Bitmap" pos:[8,8] width:208 height:64 fileName:"J:\Scripts\3dsmax\\rapidRTConform\_HEADER\\rapidConform_header.png"
)

createDialog rapidConformSettings

