rollout unnamedRollout "Untitled" width:224 height:240
(
	groupBox grp1 "DoubleSided" pos:[8,80] width:208 height:88
	checkbox chk1 "Target" pos:[24,104] width:176 height:16
	checkbox chk2 "Object" pos:[24,136] width:176 height:16
	bitmap bmp1 "Bitmap" pos:[8,8] width:208 height:64 fileName:""
	groupBox grp4 "Interactive Mode" pos:[8,176] width:208 height:56
	checkbox chk6 "Use Interactive Mode" pos:[24,200] width:176 height:16
)